### ISSUE TITLE
Error with 401

### ISSUE THREAD

**Issue by Robin1980** [akamai/AkamaiOPEN-edgegrid-ruby#14]
I wrote a program to get the cidr-blocks in 2019. And then the token is stored in the /root/.edgerc. 
It worked very well.  However, In 2021, I received some errors about 401 error as below. The token is not expired even now.  

\"title\": \"Not authorized\",\n  \"status\": 401,\n  \"detail\": \"Inactive client token\"

I noticed there were some new changes in the Python project.  Does it mean the latest fixes are not applied to this project?

Thank you.

**Comment by mattjstevens** [comment]
I believe in this case your valid client token is logically "inactive" in the Akamai identity systems.
